Hotfix 수정,취소버튼 수정
Team-B1ND/DodamDodam_WEB_MyInfo_V6 pull request #38
Opened 2024-05-16 05:59 UTC by ftery0

2024-05-17 06:25 UTC, Sanghyun0505 requested changes
코드 수정한 부분 lint 적용해주세요!
피드백 반영하시고 다시 요청해주세요~

2024-05-17 06:25 UTC, Sanghyun0505 commented on src/components/MyInfo/Contents/BusApply/BusApply.tsx
> +         {isChose ? "신청":"수정"}
개인적인 생각인데 selectedBusId === -1 ? "신청" : "수정"으로 해도 되지 않을까요?
isChose는 제가 보기엔 불필요한 state 같아요..!

2024-05-17 06:25 UTC, Sanghyun0505 commented on src/components/MyInfo/Contents/BusApply/style.ts
>            color: white;
hex로 바꿔주세용
background-color: #ff0000;
color: #fff;

2024-05-18 13:30 UTC, ftery0 commented on src/components/MyInfo/Contents/BusApply/BusApply.tsx
> +         {isChose ? "신청":"수정"}
넵 좋은 피드백 감사합니다

2024-05-18 13:30 UTC, ftery0 commented on src/components/MyInfo/Contents/BusApply/style.ts
>            color: white;
넵 변경하겠습니다

2024-05-19 23:42 UTC, Sanghyun0505 reviewed
isChose state는 사용되지 않으니 삭제해주세요

2024-05-19 23:42 UTC, Sanghyun0505 commented on src/components/MyInfo/Contents/BusApply/style.ts
>  `;
lint 적용해주세요

2024-05-19 23:42 UTC, Sanghyun0505 commented on src/components/MyInfo/Contents/BusApply/BusApply.tsx
>          >
lint 적용해주세요

2024-05-19 23:50 UTC, ftery0 commented on src/components/MyInfo/Contents/BusApply/style.ts
>  `;
넵

2024-05-19 23:50 UTC, ftery0 commented on src/components/MyInfo/Contents/BusApply/BusApply.tsx
>          >
넵

2024-05-20 08:26 UTC, Sanghyun0505 approved these changes

2024-05-20 10:23 UTC, BaekSeungHa approved these changes

2024-05-20 14:36 UTC, merged